### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/ellmar-assembly#1]
**Very well done Elliot!**

The reason behind this komplettering is that I'm unable to run your program. It gets stuck in an infinite loop. Is this a case of "but it works on my machine", or just an older version of your application?

Here are some notes on your code:

Öm...
_Your code_:
```rust
fn test() {
	parse_file();
}

fn main() {
	test();
}
```

Äsch, who am I kidding. Your code looks fine!

Please get back to me in a comment.

Can be found in Datas Sångbok:
```
When I find my code in tons of trouble,
Friends and colleagues come to me,
Speaking words of wisdom:
"Write in C."

As the deadline fast approaches,
And bugs are all that I can see,
Somewhere, someone whispers"
"Write in C."

Write in C, write in C,
Write in C, write in C.
LISP is dead and buried,
Write in C.

I used to write a lot of FORTRAN,
for science it worked flawlessly.
Try using it for graphics!
Write in C.

If you've just spent nearly 30 hours
Debugging some assembly,
Soon you will be glad to
Write in C.

Write in C, write in C,
Write In C, yeah, write in C.
Only wimps use BASIC.
Write in C.

Write in C, write in C,
Write in C, oh, write in C.
Pascal won't quite cut it.
Write in C.

Guitar Solo

Write in C, write in C,
Write in C, yeah, write in C.
Don't even mention COBOL.
Write in C.

And when the screen is fuzzy,
And the edior is bugging me.
I'm sick of ones and zeroes.
Write in C.

A thousand people people swear that T.P.
Seven is the one for me.
I hate the word PROCEDURE,
Write in C.

Write in C, write in C,
Write in C, yeah, write in C.
PL1 is 80's,
Write in C.

Write in C, write in C,
Write in C, yeah, write in C.
The government loves ADA,
Write in C.
```

**Comment by elwi7331** [comment]
My hypothesis is that you did not get stuck in an infinite loop, but rather that my code is extremely slow. This is because I thought it was a good idea to make the registers initialise with random values, and that my way of zeroing them is extremely slow.

The registers that would be random are now by default initialised to -3 instead. This should make the code run in reasonable time. At least it did for me.

**Comment by violaso** [comment]
Oh, random is evil.
